program = expressions ;
expressions = expression { ',' expression } ;
expression = binding | literal ;
binding = key ( ':' | '?:' ) literal ;
literal = [ generic ] type [ '=' value ] ;
key = [ '.' | '...' ] identifier | data ;
data = int | float | char | str | object ;
type = condition | ( array | tuple ) [ type ] ;
value = condition | code ;
generic = '<' [ expressions ] '>' ;
object = '{' [ expressions ] '}' ;
array = '[' [ expressions ] ']' ;
tuple = '(' [ expressions ] ')' ;
code = '>' literal ;
member = '.' call ;
condition = or [ '?' ( member | expression ) ] ;
or = and { ( '||' | '??' ) and } ;
and = union { '&&' union } ;
union = xor { '|' xor } ;
xor = intersect { '^' intersect } ;
intersect = equality { '&' equality } ;
equality = relation { ( '==' | '!=' | '===' | '!==' ) relation } ;
relation = range { ( '<' | '>' | '<=' | '>=' | '<:' ) range } ;
range = [ shift ] ('..' | '..=') [ shift ] ;
shift = additive { ( '<<' | '>>' | '>>>' ) additive } ;
additive = multiply { ( '+' | '-' ) multiply } ;
multiply = power { ( '*' | '/' | '%' ) power } ;
power = prefix { '**' prefix } ;
prefix = suffix | ( '++' | '--' | '+' | '-' | '~' | '!' ) prefix ;
suffix = call [ '++' | '--' ] ;
call = primary { member | array | tuple } ;
primary = key [ generic ] | tuple ;
