program = expressions ;
expressions = expression { ',' expression } ;
expression = [ literal ':' ] literal ;
literal = [ generic ] type [ '=' value ] ;
type = condition | ( array | tuple ) type ;
value = condition | code ;
code = '>' literal ;
member = '.' mapping ;
condition = or [ '?' expression ] ;
or = and { '||' and } ;
and = union { '&&' union } ;
union = xor { '|' xor } ;
xor = intersect { '^' intersect } ;
intersect = equality { '&' equality } ;
equality = relation { ( '==' | '!=' | '===' | '!==' ) relation } ;
relation = range { ( '<' | '>' | '<=' | '>=' | '<:' ) range } ;
range = shift | [ shift ] ('..' | '..=') [ shift ] ;
shift = additive { ( '<<' | '>>' | '>>>' ) additive } ;
additive = multiply { ( '+' | '-' ) multiply } ;
multiply = power { ( '*' | '/' | '%' ) power } ;
power = prefix { '**' prefix } ;
prefix = postfix | ( '++' | '--' | '+' | '-' | '~' | '!' ) prefix ;
postfix = mapping [ '++' | '--' ] ;
mapping = primary [ generic ] { member | array | tuple } [ '?' ] ;
primary = [ '...' | '.' ] ( identifier | data ) ;
data = int | float | char | str | object | array | tuple;
generic = '<' [ expressions ] '>' ;
object = '{' [ expressions ] '}' ;
array = '[' [ expressions ] ']' ;
tuple = '(' [ expressions ] ')' ;
